services:
  - type: web
    name: ltlab
    runtime: docker
    rootDir: backend
    dockerfilePath: backend/Dockerfile
    branch: main
    region: frankfurt
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: ltlab.onrender.com
      - key: DEBUG
        value: false
      - key: REDIS_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
    dockerCommand: ./start-web.sh
