# Generated by Django 5.2.15 on 2026-07-11 13:28

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=12)),
                ('hint', models.TextField()),
                ('target_formula', models.TextField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kripke_structure', models.JSONField(blank=True, null=True)),
                ('allowed_operators', models.JSONField(blank=True, default=list)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Exercises',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formula_input', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hints_used', models.IntegerField(default=0)),
                ('misconception', models.CharField(blank=True, max_length=32, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.profile')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exercises.exercise')),
            ],
            options={
                'db_table': 'Attempts',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='accounts.profile')),
                ('unlocks_after', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='exercises.topic')),
            ],
            options={
                'db_table': 'Topics',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.topic'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='uniq_topic_title_ci'),
        ),
    ]
