# Generated by Django 5.2.15 on 2026-07-05 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='attempt',
            name='hints_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='allowed_operators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='hints',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='kripke_structure',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='unlocks_after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='exercises.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
