# Generated by Django 5.2.15 on 2026-07-07 21:25

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('exercises', '0002_authoring_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='uniq_topic_title_ci'),
        ),
    ]
