# Generated by Django 5.2.15 on 2026-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_topic_created_by_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='target_formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
