# Generated by Django 5.2.16 on 2026-07-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisepart',
            name='hints',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
