# Generated by Django 5.2.16 on 2026-07-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_exercise_ever_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisepart',
            name='answer_holds',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
