# Generated by Django 5.2.16 on 2026-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_exercisepart_answer_holds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('model_check', 'Write a formula that holds'), ('judge', 'Judge formulas + counterexample'), ('path_exhibit', 'Exhibit a satisfying path'), ('english_to_formula', 'English requirement to formula'), ('build_kripke', 'Build a Kripke structure that satisfies a formula')], default='model_check', max_length=20),
        ),
    ]
