# Generated by Django 5.2.16 on 2026-07-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_alter_exercise_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('model_check', 'Write a formula that holds'), ('judge', 'Judge formulas + counterexample'), ('path_exhibit', 'Exhibit a satisfying path'), ('english_to_formula', 'English requirement to formula'), ('build_kripke', 'Build a Kripke structure that satisfies a formula'), ('buchi_construct', 'Draw a Büchi automaton for a formula'), ('buchi_word', 'Give a word a Büchi automaton accepts')], default='model_check', max_length=20),
        ),
    ]
