ACCESS_TOKEN_MAX_AGE = 60 * 60
REFRESH_TOKEN_MAX_AGE = 60 * 60 * 24 * 7
PKCE_VERIFIER_MAX_AGE = 60 * 10
PKCE_VERIFIER_COOKIE = "sb-pkce-verifier"
LOGIN_URL = "/accounts/login/"

VIEW_AS_COOKIE = "view-as"
VIEW_AS_MAX_AGE = 60 * 60 * 8
